#!/bin/sh

# Generates html from a markdown file and opens it in the browser
# before removing the evidence.
# prepend with strapdown.js header and mathjax script
cat $(dirname $(which mdgen))/mdgenerator/prepend.html > ${1}.html
# insert the markdown
#pandoc -t html --mathjax $1 >> ${1}.html
$(dirname $(which mdgen))/mdgenerator/parse.py $1 >> ${1}.html
# append with strapdown footer
cat $(dirname $(which mdgen))/mdgenerator/append.html  >> ${1}.html
